vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.background = "dark"
vim.g.colors_name = "tomorrow-night-burns"

local c = require("config.theme").colors

local s = {
  bg = c.bg,
  bg_alt = "#1b1b1b",
  bg_float = "#1e1e1e",
  bg_sel = c.selectedText,
  bg_hl = "#202020",
  border = "#3a3a3a",
  fg = c.fg,
  fg_dim = c.brightBlack,
  fg_bright = c.white,
  comment = "#708284",
}

local groups = {
  Normal = { fg = s.fg, bg = s.bg },
  NormalNC = { fg = s.fg, bg = s.bg },
  NormalFloat = { fg = s.fg, bg = s.bg_float },
  FloatBorder = { fg = s.border, bg = s.bg_float },
  FloatTitle = { fg = c.blue, bg = s.bg_float, bold = true },
  Cursor = { fg = s.bg, bg = c.cursor },
  lCursor = { fg = s.bg, bg = c.cursor },
  CursorLine = { bg = s.bg_hl },
  CursorColumn = { bg = s.bg_hl },
  ColorColumn = { bg = s.bg_alt },
  LineNr = { fg = s.fg_dim },
  CursorLineNr = { fg = c.blue, bold = true },
  SignColumn = { bg = s.bg },
  FoldColumn = { fg = s.fg_dim, bg = s.bg },
  Folded = { fg = s.comment, bg = s.bg_alt },
  VertSplit = { fg = s.border },
  WinSeparator = { fg = s.border },
  Visual = { bg = s.bg_sel },
  VisualNOS = { bg = s.bg_sel },
  Search = { fg = s.bg, bg = c.yellow },
  IncSearch = { fg = s.bg, bg = c.cursor },
  CurSearch = { fg = s.bg, bg = c.cursor },
  Substitute = { fg = s.bg, bg = c.red },
  MatchParen = { fg = c.cursor, bold = true },
  NonText = { fg = "#3a3a3a" },
  Whitespace = { fg = "#2e2e2e" },
  SpecialKey = { fg = "#3a3a3a" },
  Conceal = { fg = s.fg_dim },
  Directory = { fg = c.blue },
  Title = { fg = c.blue, bold = true },
  ErrorMsg = { fg = c.badge },
  WarningMsg = { fg = c.yellow },
  MoreMsg = { fg = c.green },
  ModeMsg = { fg = s.fg, bold = true },
  Question = { fg = c.blue },
  QuickFixLine = { bg = s.bg_sel },
  Winbar = { fg = s.fg_dim, bg = s.bg },
  WinbarNC = { fg = s.fg_dim, bg = s.bg },

  StatusLine = { fg = s.fg, bg = s.bg_alt },
  StatusLineNC = { fg = s.fg_dim, bg = s.bg_alt },
  TabLine = { fg = s.fg_dim, bg = s.bg_alt },
  TabLineSel = { fg = s.bg, bg = c.blue, bold = true },
  TabLineFill = { bg = s.bg },

  Pmenu = { fg = s.fg, bg = s.bg_float },
  PmenuSel = { fg = s.fg_bright, bg = s.bg_sel, bold = true },
  PmenuSbar = { bg = s.bg_alt },
  PmenuThumb = { bg = s.border },
  PmenuKind = { fg = c.cyan, bg = s.bg_float },
  PmenuKindSel = { fg = c.cyan, bg = s.bg_sel },
  PmenuExtra = { fg = s.fg_dim, bg = s.bg_float },
  PmenuExtraSel = { fg = s.fg_dim, bg = s.bg_sel },
  WildMenu = { fg = s.bg, bg = c.blue },

  Comment = { fg = s.comment, italic = true },
  Constant = { fg = c.blue },
  String = { fg = c.magenta },
  Character = { fg = c.magenta },
  Number = { fg = c.blue },
  Boolean = { fg = c.blue },
  Float = { fg = c.blue },
  Identifier = { fg = s.fg },
  Function = { fg = c.cyan },
  Statement = { fg = c.red },
  Conditional = { fg = c.red },
  Repeat = { fg = c.red },
  Label = { fg = c.red },
  Operator = { fg = c.yellow },
  Keyword = { fg = c.red },
  Exception = { fg = c.red },
  PreProc = { fg = c.magenta },
  Include = { fg = c.magenta },
  Define = { fg = c.magenta },
  Macro = { fg = c.magenta },
  PreCondit = { fg = c.magenta },
  Type = { fg = c.cyan },
  StorageClass = { fg = c.red },
  Structure = { fg = c.cyan },
  Typedef = { fg = c.cyan },
  Special = { fg = c.link },
  SpecialChar = { fg = c.link },
  Tag = { fg = c.blue },
  Delimiter = { fg = s.fg_dim },
  SpecialComment = { fg = s.comment, bold = true },
  Debug = { fg = c.badge },
  Underlined = { fg = c.link, underline = true },
  Ignore = { fg = s.fg_dim },
  Error = { fg = c.badge },
  Todo = { fg = s.bg, bg = c.yellow, bold = true },

  DiffAdd = { fg = c.green, bg = "#1d2420" },
  DiffChange = { fg = c.yellow, bg = "#25211c" },
  DiffDelete = { fg = c.red, bg = "#2a1c1d" },
  DiffText = { fg = c.yellow, bg = "#3a3226" },
  Added = { fg = c.green },
  Changed = { fg = c.yellow },
  Removed = { fg = c.red },

  SpellBad = { sp = c.badge, undercurl = true },
  SpellCap = { sp = c.yellow, undercurl = true },
  SpellLocal = { sp = c.cyan, undercurl = true },
  SpellRare = { sp = c.magenta, undercurl = true },

  DiagnosticError = { fg = c.badge },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.cyan },
  DiagnosticHint = { fg = s.fg_dim },
  DiagnosticOk = { fg = c.green },
  DiagnosticVirtualTextError = { fg = c.badge, bg = "#2a1616" },
  DiagnosticVirtualTextWarn = { fg = c.yellow, bg = "#2a2116" },
  DiagnosticVirtualTextInfo = { fg = c.cyan, bg = "#241e1e" },
  DiagnosticVirtualTextHint = { fg = s.fg_dim, bg = s.bg_alt },
  DiagnosticUnderlineError = { sp = c.badge, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.cyan, undercurl = true },
  DiagnosticUnderlineHint = { sp = s.fg_dim, undercurl = true },
  DiagnosticUnnecessary = { fg = s.fg_dim, italic = true },

  LspReferenceText = { bg = s.bg_sel },
  LspReferenceRead = { bg = s.bg_sel },
  LspReferenceWrite = { bg = s.bg_sel, underline = true },
  LspSignatureActiveParameter = { fg = c.cursor, bold = true },
  LspInlayHint = { fg = "#4a5a5c", bg = s.bg_alt, italic = true },
  LspCodeLens = { fg = s.fg_dim, italic = true },

  ["@variable"] = { fg = s.fg },
  ["@variable.builtin"] = { fg = c.red, italic = true },
  ["@variable.parameter"] = { fg = c.magenta },
  ["@variable.member"] = { fg = c.blue },
  ["@constant"] = { fg = c.blue },
  ["@constant.builtin"] = { fg = c.blue, italic = true },
  ["@constant.macro"] = { fg = c.magenta },
  ["@module"] = { fg = c.cyan },
  ["@label"] = { fg = c.red },
  ["@string"] = { fg = c.magenta },
  ["@string.escape"] = { fg = c.link, bold = true },
  ["@string.special"] = { fg = c.link },
  ["@string.regexp"] = { fg = c.link },
  ["@character"] = { fg = c.magenta },
  ["@boolean"] = { fg = c.blue },
  ["@number"] = { fg = c.blue },
  ["@type"] = { fg = c.cyan },
  ["@type.builtin"] = { fg = c.cyan, italic = true },
  ["@type.definition"] = { fg = c.cyan },
  ["@attribute"] = { fg = c.magenta },
  ["@property"] = { fg = c.blue },
  ["@function"] = { fg = c.cyan },
  ["@function.builtin"] = { fg = c.cyan, italic = true },
  ["@function.call"] = { fg = c.cyan },
  ["@function.macro"] = { fg = c.magenta },
  ["@function.method"] = { fg = c.cyan },
  ["@function.method.call"] = { fg = c.cyan },
  ["@constructor"] = { fg = c.cyan },
  ["@operator"] = { fg = c.yellow },
  ["@keyword"] = { fg = c.red },
  ["@keyword.function"] = { fg = c.red },
  ["@keyword.operator"] = { fg = c.yellow },
  ["@keyword.return"] = { fg = c.red, bold = true },
  ["@keyword.import"] = { fg = c.magenta },
  ["@keyword.exception"] = { fg = c.red },
  ["@keyword.conditional"] = { fg = c.red },
  ["@keyword.repeat"] = { fg = c.red },
  ["@punctuation.delimiter"] = { fg = s.fg_dim },
  ["@punctuation.bracket"] = { fg = s.fg_dim },
  ["@punctuation.special"] = { fg = c.link },
  ["@comment"] = { fg = s.comment, italic = true },
  ["@comment.error"] = { fg = s.bg, bg = c.badge, bold = true },
  ["@comment.warning"] = { fg = s.bg, bg = c.yellow, bold = true },
  ["@comment.todo"] = { fg = s.bg, bg = c.cyan, bold = true },
  ["@comment.note"] = { fg = s.bg, bg = c.green, bold = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading"] = { fg = c.blue, bold = true },
  ["@markup.heading.1"] = { fg = c.blue, bold = true },
  ["@markup.heading.2"] = { fg = c.cyan, bold = true },
  ["@markup.heading.3"] = { fg = c.magenta, bold = true },
  ["@markup.heading.4"] = { fg = c.yellow, bold = true },
  ["@markup.quote"] = { fg = s.comment, italic = true },
  ["@markup.link"] = { fg = c.link, underline = true },
  ["@markup.link.label"] = { fg = c.blue },
  ["@markup.link.url"] = { fg = c.link, underline = true },
  ["@markup.raw"] = { fg = c.magenta },
  ["@markup.list"] = { fg = c.red },
  ["@markup.list.checked"] = { fg = c.green },
  ["@markup.list.unchecked"] = { fg = s.fg_dim },
  ["@diff.plus"] = { fg = c.green },
  ["@diff.minus"] = { fg = c.red },
  ["@diff.delta"] = { fg = c.yellow },
  ["@tag"] = { fg = c.red },
  ["@tag.builtin"] = { fg = c.red },
  ["@tag.attribute"] = { fg = c.blue },
  ["@tag.delimiter"] = { fg = s.fg_dim },

  ["@lsp.type.class"] = { link = "@type" },
  ["@lsp.type.decorator"] = { link = "@attribute" },
  ["@lsp.type.enum"] = { link = "@type" },
  ["@lsp.type.enumMember"] = { link = "@constant" },
  ["@lsp.type.interface"] = { link = "@type" },
  ["@lsp.type.macro"] = { link = "@function.macro" },
  ["@lsp.type.method"] = { link = "@function.method" },
  ["@lsp.type.namespace"] = { link = "@module" },
  ["@lsp.type.parameter"] = { link = "@variable.parameter" },
  ["@lsp.type.property"] = { link = "@property" },
  ["@lsp.type.struct"] = { link = "@type" },
  ["@lsp.type.type"] = { link = "@type" },
  ["@lsp.type.typeParameter"] = { link = "@type.definition" },
  ["@lsp.type.variable"] = { link = "@variable" },
  ["@lsp.mod.readonly"] = { link = "@constant" },
  ["@lsp.mod.deprecated"] = { strikethrough = true },

  GitSignsAdd = { fg = c.green },
  GitSignsChange = { fg = c.yellow },
  GitSignsDelete = { fg = c.red },
  GitSignsCurrentLineBlame = { fg = s.fg_dim, italic = true },

  SnacksNormal = { fg = s.fg, bg = s.bg_float },
  SnacksWinBar = { fg = c.blue, bg = s.bg_float, bold = true },
  SnacksBackdrop = { bg = "#0b0b0b" },
  SnacksPickerDir = { fg = s.fg_dim },
  SnacksPickerMatch = { fg = c.cursor, bold = true },
  SnacksPickerSelected = { fg = c.blue },
  SnacksIndent = { fg = "#252525" },
  SnacksIndentScope = { fg = c.red },
  SnacksDashboardHeader = { fg = c.blue },
  SnacksDashboardIcon = { fg = c.cyan },
  SnacksDashboardDesc = { fg = s.fg },
  SnacksDashboardKey = { fg = c.yellow },
  SnacksNotifierInfo = { fg = c.cyan, bg = s.bg_float },
  SnacksNotifierWarn = { fg = c.yellow, bg = s.bg_float },
  SnacksNotifierError = { fg = c.badge, bg = s.bg_float },

  BlinkCmpMenu = { fg = s.fg, bg = s.bg_float },
  BlinkCmpMenuBorder = { fg = s.border, bg = s.bg_float },
  BlinkCmpMenuSelection = { bg = s.bg_sel, bold = true },
  BlinkCmpLabel = { fg = s.fg },
  BlinkCmpLabelMatch = { fg = c.cursor, bold = true },
  BlinkCmpLabelDeprecated = { fg = s.fg_dim, strikethrough = true },
  BlinkCmpKind = { fg = c.cyan },
  BlinkCmpSource = { fg = s.fg_dim },
  BlinkCmpDoc = { fg = s.fg, bg = s.bg_float },
  BlinkCmpDocBorder = { fg = s.border, bg = s.bg_float },
  BlinkCmpSignatureHelp = { fg = s.fg, bg = s.bg_float },
  BlinkCmpSignatureHelpActiveParameter = { fg = c.cursor, bold = true },
  BlinkCmpGhostText = { fg = "#3f4a4c", italic = true },

  WhichKey = { fg = c.blue },
  WhichKeyGroup = { fg = c.cyan },
  WhichKeyDesc = { fg = s.fg },
  WhichKeySeparator = { fg = s.fg_dim },
  WhichKeyFloat = { bg = s.bg_float },
  WhichKeyBorder = { fg = s.border, bg = s.bg_float },

  TroubleNormal = { fg = s.fg, bg = s.bg_alt },
  TroubleText = { fg = s.fg },
  TroubleCount = { fg = c.magenta, bg = s.bg_sel },

  BufferLineFill = { bg = s.bg_alt },
  BufferLineBufferSelected = { fg = s.fg_bright, bg = s.bg, bold = true },
  BufferLineIndicatorSelected = { fg = c.blue, bg = s.bg },

  NoiceCmdlinePopupBorder = { fg = s.border },
  NoiceCmdlineIcon = { fg = c.blue },
  NoiceConfirmBorder = { fg = s.border },

  FlashLabel = { fg = s.bg, bg = c.cursor, bold = true },
  FlashMatch = { fg = s.fg_bright, bg = s.bg_sel },

  IlluminatedWordText = { bg = s.bg_sel },
  IlluminatedWordRead = { bg = s.bg_sel },
  IlluminatedWordWrite = { bg = s.bg_sel, underline = true },

  TreesitterContext = { bg = s.bg_alt },
  TreesitterContextLineNumber = { fg = s.fg_dim, bg = s.bg_alt },

  RenderMarkdownH1Bg = { fg = c.blue, bg = "#2a1a1b" },
  RenderMarkdownH2Bg = { fg = c.cyan, bg = "#241c1c" },
  RenderMarkdownH3Bg = { fg = c.magenta, bg = "#201b1b" },
  RenderMarkdownCode = { bg = s.bg_alt },
  RenderMarkdownBullet = { fg = c.red },
}

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end

local ansi = {
  c.black,
  c.red,
  c.green,
  c.yellow,
  c.blue,
  c.magenta,
  c.cyan,
  c.white,
  c.brightBlack,
  c.brightRed,
  c.brightGreen,
  c.brightYellow,
  c.brightBlue,
  c.brightMagenta,
  c.brightCyan,
  c.brightWhite,
}
for i, color in ipairs(ansi) do
  vim.g["terminal_color_" .. (i - 1)] = color
end
