-- Generated by modules/nixos/theme/theme.nix.

local fallback = {
  name = "tomorrow-night-burns",
  colors = {
    bg = "#151515",
    fg = "#a1b0b8",
    cursor = "#ff443e",
    selection = "#b0bec5",
    selectedText = "#2a2d32",
    link = "#ea4047",
    badge = "#ff0000",
    black = "#252525",
    red = "#832e31",
    green = "#a63c40",
    yellow = "#d3494e",
    blue = "#fc595f",
    magenta = "#df9395",
    cyan = "#ba8586",
    white = "#f5f5f5",
    brightBlack = "#5d6f71",
    brightRed = "#832e31",
    brightGreen = "#a63c40",
    brightYellow = "#d2494e",
    brightBlue = "#fc595f",
    brightMagenta = "#df9395",
    brightCyan = "#ba8586",
    brightWhite = "#f5f5f5",
  },
}

local M = fallback

local ok, loaded = pcall(dofile, "/etc/nvim-theme.lua")
if ok and type(loaded) == "table" and type(loaded.name) == "string" then
  M = {
    name = loaded.name,
    colors = vim.tbl_extend("force", fallback.colors, loaded.colors or {}),
  }
end

return M
