name: Test Installation Scripts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-installation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Initialize Submodules
      run: |
        git submodule update --init --recursive

    - name: Run install.sh in Arch Linux Docker
      run: |
        docker run --rm -v ${{ github.workspace }}/dotfiles:/dotfiles archlinux:latest bash -c "\
          pacman -Syu --noconfirm && \
          pacman -S --noconfirm --needed sudo git base-devel curl && \
          cd /dotfiles && \
          bash install.sh\
        "